app/models/personaje.py
import datetime
import requests


class Personaje:
    API = "https://rickandmortyapi.com/api/character"

    def __init__(self, name, status, especie, genero, imagen) -> None:
        self.name = name
        self.status = status
        self.especie = especie
        self.genero = genero
        self.imagen = imagen

    def obtener_personajes(self, cantidad_personajes):
        response = requests.get(self.API + '/' + cantidad_personajes)
        lista_personaje = response.json()

        return lista_personaje

    def to_json(self):
        return {
            'name': self.name,
            'status': self.status,
            'especie': self.especie,
            'genero': self.genero,
            'imagen': self.imagen
        }

app/__init__.py
from flask import Flask
from .config import Config
from flask_bootstrap import Bootstrap

from app.routes.personaje import bp_personaje


def create_app():
    app = Flask(__name__)

    app.config.from_object(Config)
    app.register_blueprint(bp_personaje)

    Bootstrap(app)

    return app

app/routes/personaje.py
from flask import Blueprint, render_template, request, flash, url_for, redirect

from app.models.personaje import Personaje
from app.db import db

bp_personaje = Blueprint('bp_personaje', __name__)


@bp_personaje.route('/')
def index():
    personajes = db.personaje.find()
    return render_template('index.html', personajes=personajes)


@bp_personaje.route('/insertar', methods=['GET', 'POST'])
def insertar():
    if request.method == 'POST':
        lista_p = []
        cantidad_pages = int(request.form.get('cantidad_pages'))

        if cantidad_pages == 42:
            cantidad_pages = (cantidad_pages * 20) - 14
        else:
            cantidad_pages = cantidad_pages * 20

        for i in range(1, cantidad_pages + 1):
            lista_p.append(i)

        count_personajes = ",".join([str(num) for num in lista_p])

        personaje = Personaje("", "", "", "", "")
        lista_personajes = personaje.obtener_personajes(count_personajes)

        db.personaje.insert_many(lista_personajes)

        flash('Felicidades!, Se generó la BD correctamente.', 'success')
        # return redirect(url_for('bp_personaje.index'))

    return render_template('insertar.html')


@bp_personaje.route('/perfil')
def perfil():
    id = request.args.get('id')

    personaje = db.personaje.find_one({'id': int(id)})
    return render_template('perfil.html', personaje=personaje)

app/templates/base.html
{% extends "bootstrap/base.html" %}
{% block body %}
<div class="container">
    {% for message in get_flashed_messages(category_filter=['success']) %}
    <div class="alert alert-success alert-dismissible">
        <button class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}
    {% for message in get_flashed_messages(category_filter=['error']) %}
    <div class="alert alert-danger alert-dismissible">
        <button class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}
    {% block content %} {% endblock %}
</div>
{% block scripts %}
{{ super() }}
{% endblock %}
{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% block content %}
<h1>Lista de Personajes</h1>
<button type="button" class="btn btn-dark"><a href="{{ url_for('bp_personaje.insertar') }}">Generar BD</a></button>
<br>
<br>
<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th hidden>id</th>
                <th>imagen</th>
                <th>name</th>
                <th>status</th>
                <th>especie</th>
                <th>genero</th>
                <th>Visualizar</th>
            </tr>
        </thead>
        <tbody>
            {% for personaje in personajes %}
            <tr>
                <td hidden>{{ personaje.id }}</td>
                <td><img src="{{ personaje.image }}" alt="" style="width: 100px;"></td>
                <td>{{ personaje.name }}</td>
                <td>{{ personaje.status }}</td>
                <td>{{ personaje.species }}</td>
                <td>{{ personaje.gender }}</td>
                <td>
                    <button type="button" class="btn btn-outline-danger"><a
                            href="{{ url_for('bp_personaje.perfil', id=personaje.id) }}">Perfil</a></button>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

app/templates/insertar.html
{% extends "base.html"%}
{% block content %}
<form action="{{url_for('bp_personaje.insertar')}}" method="post">
    <div class="card" style="width: 100vw; height: 80vh; text-align: center; margin-top: 100px;">
        <h2>Generar BD - API de Rick and Morty</h2>
        <br><br>
        <div>
            Cantidad Paginas:<br>
            <input type="number" name="cantidad_pages" placeholder="Ingrese cantidad de paginas a consumir"
                style="border: 1px solid gray; border-radius: 5px; padding: 10px; width: 300px;">
        </div>
        <br><br>
        <button type=" submit" class="btn btn-primary btn-lg"><strong>Iniciar</strong></button>
        <br><br>
        <div><a href="{{url_for('bp_personaje.index')}}">regresar</a></div>
    </div>
</form>
{% endblock %}

app/templates/perfil.html
{% extends "base.html"%}
{% block content %}
<div>
    <h2>Perfil Personaje</h2>
    <div><a href="{{url_for('bp_personaje.index')}}">regresar</a></div>
    <br>
    <img src="{{ personaje.image }}" alt=""><br>
    <div>
        <strong>name:</strong> {{ personaje.name }}<br>
        <strong>status:</strong> {{ personaje.status }}<br>
        <strong>species:</strong> {{ personaje.species }}<br>
        <strong>gender:</strong> {{ personaje.gender }}
    </div>
</div>
{% endblock %}